### ISSUE TITLE
Memory limit 4048m?

### ISSUE THREAD

**Issue by BCsabaEngine** [fphgov/test-booking#1]
Kicsit fura, nem elgepeles véletlenül a limitation-ben?
`4048M`

**Comment by icetee** [comment]
De igen, `4096M` lenne. De lehet így is túl van skálázva egy picit.

**Comment by icetee** [comment]
Köszönjük a visszajelzést. Módosítottunk ezen a paraméteren. https://github.com/fphgov/test-booking/commit/7d77c05c4835a9dac4c4320fd425342b65e1ae11
